data:
  env: NaN
  user:
    username: NaN
    password: NaN

server:
  port: 3011
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"